name: multiline
description: >
  Provides convenient access to multiline String records with method extensions.
version: 2.0.0
repository: https://github.com/PlugFox/multiline/tree/master
issue_tracker: https://github.com/PlugFox/multiline/issues
homepage: https://github.com/PlugFox/multiline
#author: Plague Fox <plugfox@gmail.com>
#documentation: https://pub.dev/documentation/multiline/latest

#publish_to: 'none' 

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test_coverage: ^0.4.3
  test: ^1.15.3