name: multiline
description: >
  Provides convenient access to multiline String records with method extensions.
version: 1.0.1+1
#author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/PlugFox/multiline

#publish_to: 'none' 

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:

dev_dependencies:
  test: any

dependency_overrides:
